### ISSUE TITLE
Move to TypeTags and ClassTags breaks compatibility with chill-avro, and may break use in Storm topologies

### ISSUE THREAD

**Issue by miguno** [twitter/bijection#181]
I noticed that a commit made it into the recently released version 0.7.0 that changes Bijection to use TypeTags and ClassTags instead of Manifests:

* [Move to ClassTags and TypeTags](https://github.com/twitter/bijection/commit/4ccf11709901f085360c6302ac696779f50bec2c)

**What has changed in Bijection 0.7.0?**

Full details are in the commit linked above, but here's a short snippet:

```git
diff --git a/bijection-avro/src/main/scala/com/twitter/bijection/avro/AvroCodecs.scala b/bijection-avro/src/main/scala/com/twitter/bijection/avro/AvroCodecs.scala
index 54e70e1..1f382fa 100644
--- a/bijection-avro/src/main/scala/com/twitter/bijection/avro/AvroCodecs.scala
+++ b/bijection-avro/src/main/scala/com/twitter/bijection/avro/AvroCodecs.scala
@@ -24,6 +24,7 @@ import org.apache.avro.generic.{ GenericDatumReader, GenericDatumWriter, Generic
 import org.apache.avro.Schema
 import org.apache.avro.io.{ DecoderFactory, DatumReader, EncoderFactory, DatumWriter }
 import Injection.utf8
+import scala.reflect._

 /**
  * Factory providing various avro injections.
@@ -37,8 +38,8 @@ object SpecificAvroCodecs {
    * @tparam T compiled Avro record
    * @return Injection
    */
-  def apply[T <: SpecificRecordBase: Manifest]: Injection[T, Array[Byte]] = {
-    val klass = manifest[T].erasure.asInstanceOf[Class[T]]
+  def apply[T <: SpecificRecordBase: ClassTag]: Injection[T, Array[Byte]] = {
+    val klass = classTag[T].runtimeClass.asInstanceOf[Class[T]]
     new SpecificAvroCodec[T](klass)
   }

  ...rest omitted...
```

**(Confirmed) Breaks compatibility for chill-avro**

_In short: This is caused by chill/chill-avro using Manifests, whereas Bijection 0.7.0 uses TypeTags/ClassTags now._

First, I noticed that this apparently breaks chill-avro as of 0.4.0+ because chill-avro still uses Manifests instead of TypeTags: see [AvroSerializer.scala](https://github.com/twitter/chill/blob/develop/chill-avro/src/main/scala/com/twitter/chill/avro/AvroSerializer.scala#L31).

Compiling my test code (taken from [kafka-storm-starter](https://github.com/miguno/kafka-storm-starter)) works, but running a Storm topology that uses this code (e.g. [this AvroDecoderBolt[T] test](https://github.com/miguno/kafka-storm-starter/blob/develop/src/test/scala/com/miguno/kafkastorm/integration/KafkaStormSpec.scala#L117) fails at runtime with an exception similar to the following.  This error is logged by Storm (`b.s.d.worker` = `backtype.storm.*.worker`):

```
2014-09-10 11:51:48 b.s.d.worker [ERROR] Error on initialization of server mk-worker
java.lang.NoSuchMethodError: com.twitter.bijection.avro.SpecificAvroCodecs$.apply(Lscala/reflect/Manifest;)Lcom/twitter/bijection/Injection;
	at com.twitter.chill.avro.AvroSerializer$.SpecificRecordSerializer(AvroSerializer.scala:32) ~[chill-avro-0.4.0.jar:0.4.0]
	at com.miguno.kafkastormstarter.TweetAvroKryoDecorator.decorate(TweetAvroKryoDecorator.scala:11) ~[classes/:na]
```

The `TweetAvroKryoDecorator` code looks as follows:

```scala
class TweetAvroKryoDecorator extends IKryoDecorator {
  override def decorate(k: Kryo) {
    k.register(classOf[Tweet], AvroSerializer.SpecificRecordSerializer[Tweet]) // <<< this line is #11 in the stack trace above
    KryoSerializer.registerAll(k)
  }
}
```

*Affected chill-avro versions:*  I'd say all of them.  The latest version of chill-avro (0.5.0) suffers from the same problem (use of Manifests), though I couldn't test it in practice because of [chill issue #198](https://github.com/twitter/chill/issues/198) (I reported this earlier today).  Still, this part of the chill-avro code apparently hasn't changed between 0.4.0, 0.5.0, and latest `develop` branch, so the later versions are affected as well.

**(Potentially) breaks Storm topologies**

_In short: This is caused by Bijection 0.7.0 using TypeTags/ClassTags now, which are affected by a known Scala bug in versions < 2.11.2 ([SI-5919](https://issues.scala-lang.org/browse/SI-5919)).  In affected Scala versions TypeTags are actually not serializable even though they should be._

I say "potentially" because it depends on the actual Storm topology code.  In short, whenever your Storm topology code -- bolts etc. -- must make use of TypeTags/ClassTags (e.g. because you want to parameterize classes with Avro record types, which are then encoded/decoded generically by Chill and Bijection) -- the topology will fail at run-time.  Hence this is issue is only partly related to Bijection/Chill, and affects those that want to use Scala's type system to minimize code duplication (e.g. only write a single `AvroDecoderBolt[T]` that can handle all kinds of Avro records you can throw at it).  If you're an Avro-centric data shop, however, lack of support for this functionality hurts a lot (and notably because prior versions of Bijection/Chill have worked seamlessly so far).

Even *if* chill-avro were changed to use TypeTags and ClassTags (to be compatible with Bijection 0.7.0), there is potentially another problem:  There is a known Scala bug ([SI-5919](https://issues.scala-lang.org/browse/SI-5919)) that prevents TypeTags from being serializable even though they are supposed to.  This bug affects all versions of Scala < 2.11.2.

What does this mean?  If you were to use Bijection and/or chill-avro -- at least in a setup similar to mine where I use e.g. parameterized Avro bolts such as `AvroDecoderBolt[T]` with `[T <: SpecificRecordBase]` for encoding/decoding -- your Storm topologies will fail at runtime for Scala versions < 2.11.2.  (The code will successfully compile though.)  This parametric approach with `[T <: SpecificRecordBase]` is very similar to how Bijection itself is implemented, btw (so I hope this sub-problem does catch your interest even though it is only partly related to Bijection/Chill itself :-P).

Manifests were/are properly serializable, hence using Manifests in Storm code was safe (as Storm serializes/deserializes your code), and for Scala versions < 2.11.2 actually the only known workaround.

Here is some further background, taken from [AvroDecoderBolt[T]](https://github.com/miguno/kafka-storm-starter/blob/develop/src/main/scala/com/miguno/kafkastorm/storm/AvroDecoderBolt.scala#L43):

```scala
  // Note: Ideally we would like to use TypeTag's instead of Manifest's here.  Doing so would only require replacing
  // `manifest[T]` with `typeOf[T]`, and adding AvroDecoderBolt[T : TypeTag].  Unfortunately there is a known
  // serialization bug in Scala's TypeTag implementation that will trigger runtime exceptions when submitting/running
  // this class in a Storm topology.
  //
  // See "SI-5919: Type tags (and Exprs as well) should be serializable" (https://issues.scala-lang.org/browse/SI-5919)
```

**How to fix**

Option A: We could update chill-avro to move from Manifests to TypeTags/ClassTags, which would make it compatible with Bijection 0.7.0.  However, this would break (at least some, see above) use cases of Bijection/Chill in Storm topologies when using < Scala 2.11.2 due to SI-5919.

Option B: Revert Bijection to use Manifests again, which fixes the compatibility with chill-avro and also fixes the "serialization/deserialization" related compatibility with Storm for Scala versions 2.10.x and 2.11.x.  Moving back from Manifests to TypeTags/ClassTags could be done once Scala 2.11.2+ (and its ecosystem) becomes more widespread.

Any further options?

Preferably I'd pick option B (use Manifests again for the meantime) as it will address all the current issues, and there might be further issues lurking thanks to SI-5919 then the serde-related Storm problem I observed (that is, other apps that require serde of TypeTags/ClassTags may fail similarly when using Scala versions that are affected by SI-5919).

**How to reproduce (details)**

* Code: [kafka-storm-starter](https://github.com/miguno/kafka-storm-starter)
* Environment:
    * Java 7
    * Scala 2.10.4
    * Mac OS X 10.9 as well as RHEL/CentOS 6
    * Bijection 0.7.0, chill-avro 0.4.0
    * Storm 0.9.2-incubating (earlier versions should exhibit the same problem)

In `build.sbt` change:

```
  "com.twitter" %% "bijection-core" % "0.6.3",
  "com.twitter" %% "bijection-avro" % "0.6.3",
```

to

```
  "com.twitter" %% "bijection-core" % "0.7.0",
  "com.twitter" %% "bijection-avro" % "0.7.0",
```

Then run `./sbt clean test`.

You will see the following error in the test output:

```
[info] KafkaStormSpec:
[info] Feature: AvroDecoderBolt[T]
2014-09-10 13:23:01 b.s.d.worker [ERROR] Error on initialization of server mk-worker
java.lang.NoSuchMethodError: com.twitter.bijection.avro.SpecificAvroCodecs$.apply(Lscala/reflect/Manifest;)Lcom/twitter/bijection/Injection;
	at com.twitter.chill.avro.AvroSerializer$.SpecificRecordSerializer(AvroSerializer.scala:32) ~[chill-avro-0.4.0.jar:0.4.0]
	at com.miguno.kafkastorm.storm.TweetAvroKryoDecorator.decorate(TweetAvroKryoDecorator.scala:11) ~[classes/:na]
	at backtype.storm.serialization.SerializationFactory.getKryo(SerializationFactory.java:112) ~[storm-core-0.9.2-incubating.jar:0.9.2-incubating]
	at backtype.storm.serialization.KryoValuesDeserializer.<init>(KryoValuesDeserializer.java:33) ~[storm-core-0.9.2-incubating.jar:0.9.2-incubating]
	at backtype.storm.serialization.KryoTupleDeserializer.<init>(KryoTupleDeserializer.java:39) ~[storm-core-0.9.2-incubating.jar:0.9.2-incubating]
	at backtype.storm.daemon.executor$mk_executor_data$fn__3189.invoke(executor.clj:212) ~[storm-core-0.9.2-incubating.jar:0.9.2-incubating]
	at backtype.storm.util$assoc_apply_self.invoke(util.clj:816) ~[storm-core-0.9.2-incubating.jar:0.9.2-incubating]
	at backtype.storm.daemon.executor$mk_executor_data.invoke(executor.clj:212) ~[storm-core-0.9.2-incubating.jar:0.9.2-incubating]
	at backtype.storm.daemon.executor$mk_executor.invoke(executor.clj:317) ~[storm-core-0.9.2-incubating.jar:0.9.2-incubating]
	at backtype.storm.daemon.worker$fn__4527$exec_fn__1096__auto____4528$iter__4533__4537$fn__4538.invoke(worker.clj:375) ~[storm-core-0.9.2-incubating.jar:0.9.2-incubating]
```

FYI:  The KafkaStormSpec is an integration tests that spawns in-memory instances of Kafka, ZooKeeper, and Storm.  It will then execute a simple topology that reads from Kafka, and writes to Kafka.  The bolts being used are of the form `AvroDecoderBolt[T <: SpecificRecordBase]`, that is they are parameterized to encode/decode "your" custom Avro schema/records.  All the encoding/decoding magic is done via Chill/Bijection.  See [AvroDecoderBolt[T]](https://github.com/miguno/kafka-storm-starter/blob/develop/src/main/scala/com/miguno/kafkastorm/storm/AvroDecoderBolt.scala#L43) for an example.

**Comment by MansurAshraf** [comment]
@miguno I think this is fixed? Let me know so I can close this issue

**Comment by miguno** [comment]
I'll take another look!

**Comment by miguno** [comment]
@MansurAshraf I haven't had the chance to re-test, so I'll close this issue for the time being (and re-open if/when needed).
