### ISSUE TITLE
Injection.invert[String, Array[Byte]](Array[Byte](1, 2, 3, -1, -2, -127)) produces a string that cannot be inverted back

### ISSUE THREAD

**Issue by ashwinraghav** [twitter/bijection#199]
![screen shot 2015-02-23 at 3 17 27 pm](https://cloud.githubusercontent.com/assets/211174/6340151/84bf6656-bb71-11e4-991b-92b53cb96e99.png)

**Comment by johnynek** [comment]
I think we need to validate that the byte string is valid UTF-8. It seems Java does not by default. That is really surprising. Why String does not throw an exception is really beyond me here.

**Comment by ashwinraghav** [comment]
One way to fix this is discussed  <a href="https://gerrit.twitter.biz/#/c/61275/">here</a>
TLDR;
``` 
(new String(Array[Byte](1,2,3,-1,-2,-127).map(_.toChar))).toCharArray.map(_.toByte)
```
Don't depend on an encoding. Before the transformation, convert to characters arrays.
The string constructor applies no encoding to char arrays.

**Comment by ianoc** [comment]
Thats not going to be correct for characters which take more than one byte though is it?

**Comment by mosesn** [comment]
Java lets you report failures in other [ways][0].

[0]: http://docs.oracle.com/javase/7/docs/api/java/nio/charset/CharsetDecoder.html#onUnmappableCharacter(java.nio.charset.CodingErrorAction)

**Comment by johnynek** [comment]
@mosesn that looks like the way to go.
