### ISSUE TITLE
No published version of bijection-scrooge for Scala 2.11?

### ISSUE THREAD

**Issue by stephanh** [twitter/bijection#209]
There doesn't seem to be a version of bijection-scroobe for Scala 2.11 http://search.maven.org/#search%7Cga%7C1%7Cbijection-scrooge while there are other Scala 2.11 bijection projects. Is that intentional?

**Comment by ianoc** [comment]
Historical artifact at this point. Would happily take a pr  to fix that.
When we published 2.11 bijection there wasn't a 2.11 scrooge-serializer
package.

**Comment by stephanh** [comment]
Ok.

It looks already fixed on develop where bijectionScrooge depends on `3.17.0` which is the Scala 2.10/2.11 version.

I noticed that it only depends on libthrift `0.6.2` which Scrooge `3.17.0` depends on libthrift `0.8.0`.

Are you planning on releasing a new version of bijection very soon or should I do a PR against master just to bump the scrooge versions?

Do you want me to bump the libthrift versions on develop?

**Comment by ianoc** [comment]
We internally mostly use thrift at 0.5.x for some fun historical reasons. So its better if users just bump that locally as they need. Scrooge I think will work against multiple versions, it will transitively bump anything it touches anyway.

We don't do PR's directly against master, it only gets updated as part of the release cycle. As for the next rls, not actually sure when, but should be soon.

**Comment by stephanh** [comment]
Any chance you could just publish a release for bijection-scrooge for Scala 2.11? :smile: We are trying to upgrade to 2.11.

**Comment by MansurAshraf** [comment]
Why don't you do a local release till we get the official release out? At least it will unblock you 






On Mon, Apr 27, 2015 at 6:17 PM -0700, "Stephan Hoermann" <notifications@github.com> wrote:












Any chance you could just publish a release for bijection-scrooge for Scala 2.11?  We are trying to upgrade to 2.11.

**Comment by stephanh** [comment]
I was hoping to be able to depend on a proper release but I will do that instead.
