### ISSUE TITLE
ScroogeCodecLaws is flaky

### ISSUE THREAD

**Issue by jnievelt** [twitter/bijection#211]
Looks like we're testing JsonScalaCodec beyond its limits.  Various unicode strings can fail to round-trip, causing the test to (usually) fail.  This seems to be a limitation of the underlying protocol/serializer, and the correct approach is probably to constrain the set of strings tested.

**Comment by ianoc** [comment]
This was fixed in #214

**Comment by sritchie** [comment]
I'm scrounging around for scala issues. Closing this one, since it looks like it's fixed.

**Comment by johnynek** [comment]
Nice to see you around here, @sritchie !
