### ISSUE TITLE
publish 0.9.2 with #243 fix

### ISSUE THREAD

**Issue by johnynek** [twitter/bijection#244]
see: #243

**Comment by johnynek** [comment]
mima passes as it should:

`[success] Total time: 28 s, completed Feb 16, 2016 1:35:48 PM`

**Comment by rubanm** [comment]
@johnynek SGTM

**Comment by jnievelt** [comment]
SGTM

**Comment by johnynek** [comment]
https://github.com/twitter/bijection/releases/tag/v0.9.2
