### ISSUE TITLE
Create Bijections for JavaFuture to CompletableFuture

### ISSUE THREAD

**Issue by renanpalmeira** [twitter/bijection#280]
I had to go back to Java in some projects... I had to used AWS library and he return Future (java future), this is not cool... i'm using Spring Boot 2.0 with Netty and to take benefit in using this stack, i needed convert Future (from AWS library) to CompletableFuture, follow in https://github.com/renanpalmeira/alfred/blob/master/alfred-templates/src/main/scala/com/alfred/templates/conversions/Conversions.scala#L35-L50, this is a relevant PR to add in bijection library? 

Also i created bijections to reactive types of Reactor library (a reactive library for Spring Boot) https://github.com/renanpalmeira/alfred/blob/master/alfred-templates/src/main/scala/com/alfred/templates/conversions/Conversions.scala#L13-L33 and if is relevant follow link about types (Flow and Mono) of Reactor https://spring.io/blog/2016/04/19/understanding-reactive-types#reactive-apis

Sorry if this a idiot issue for contribute to library  :sweat_smile:

Thanks,

**Comment by johnynek** [comment]
we have these:

https://github.com/twitter/bijection/blob/develop/bijection-util/src/main/scala/com/twitter/bijection/twitter_util/JavaFutureConverter.scala

but having similar to scala future, would be nice and could be in bijection core.

we could definitely have a bijection-aws module. That could be pretty interesting. Are there other conversions we could put in there?
 
Not an idiotic thing at all. PRs welcomed!

**Comment by renanpalmeira** [comment]
Ohh i did not know about this file JavaFutureConverter... i will try move my method to this file with tests and open a PR... And about bijection-aws maybe is interest... this library in java is some verbose (like everything in java haha) https://github.com/RenanPalmeira/alfred/blob/master/alfred-templates/src/main/java/com/alfred/templates/controller/TemplateController.java#L85-L95 and i trying reduce some things with using a some libraries in scala https://github.com/RenanPalmeira/alfred/blob/master/alfred-templates/src/main/java/com/alfred/templates/controller/TemplateController.java#L61-L65... but the more difficult about her is that any return of methods async from her is a Future while at least for me and for majority is try use a CompletableFuture for all.

even if it is not possible to exist bijection-aws, thanks for the reply and I write a simple PR for this convert from Future to CompletableFuture :smiley:

**Comment by renanpalmeira** [comment]
Hi @johnynek ,

I using for this code https://github.com/renanpalmeira/alfred/blob/master/alfred-templates/src/main/scala/com/alfred/templates/conversions/Conversions.scala#L37-L48 in Scala version 2.12 and the bijection use the Scala version of 2.11.8 (with cross Scala). And in Scala 2.11 i get this error when i using ``` () => {} ```, follow error: 

```
[error]   UtilBijections.scala:175: overloaded method value supplyAsync with alternatives:
[error]   [U](x$1: java.util.function.Supplier[U], x$2: java.util.concurrent.Executor)java.util.concurrent.CompletableFuture[U] <and>
[error]   [U](x$1: java.util.function.Supplier[U])java.util.concurrent.CompletableFuture[U]
[error]  cannot be applied to (() => T)
[error]       override def apply(javaFuture: JavaFuture[T]): JavaCompletableFuture[T] = JavaCompletableFuture.supplyAsync(() => {
[error]                                                                                                       ^
```

Can you help me? If it will not disturb you

**Comment by renanpalmeira** [comment]
Hi again @johnynek ,

I think finished my first contribute adding bijection to convert java future to completable future... in https://github.com/RenanPalmeira/bijection/commit/cf931331cd4ef7fe72c6ee8607d9de6692044131

Can i open a PR?

**Comment by mosesn** [comment]
@RenanPalmeira please make a PR!  if there are issues we can workshop it in the PR.
