### ISSUE TITLE
Support for Scala 2.13 RC1 and beyond

### ISSUE THREAD

**Issue by skonto** [twitter/bijection#285]
This blocks chill https://github.com/twitter/chill/issues/316 which blocks Spark 2.13 support

**Comment by johnynek** [comment]
PRs welcome.

**Comment by skonto** [comment]
@johnynek yes but I guess first need to fix `scrooge`.

**Comment by SethTisue** [comment]
scrooge ticket is https://github.com/twitter/scrooge/issues/308

**Comment by nevillelyh** [comment]
@johnynek @mosesn mind adding me as a repo collaborator? Wanna help with fixing up builds, scala-steward PRs and eventually 2.13 support.

**Comment by mosesn** [comment]
I don't know what the process is for that, maybe @johnynek knows?  I can also ask around inside of Twitter.

**Comment by johnynek** [comment]
@decause has added @nevillelyh to Algebird. I'd love to see him added here as well if he is willing to help.

**Comment by mosesn** [comment]
ok, @decause is OOO right now, but I'll nudge him when he gets back.

**Comment by mosesn** [comment]
@nevillelyh I think you should be a collaborator now, can you double check your permissions?  @decause got back from OOO and immediately tackled it

**Comment by SethTisue** [comment]
I see https://search.maven.org/artifact/com.twitter/bijection_2.13/0.9.7/ — should this ticket be closed, or is something left undone? (the repo readme still says "Every artifact is published against Scala "2.10", "2.11" and "2.12"")

**Comment by nevillelyh** [comment]
Sorry haven't paid attention to these in a while. Yes this can be closed.

**Comment by nevillelyh** [comment]
Also fixed the README, good catch!
https://github.com/twitter/bijection/pull/418
