### ISSUE TITLE
Why aren't there new releases?

### ISSUE THREAD

**Issue by nartamonov** [twitter/bijection#364]
It seems that library is more or less in active developent (or maintenance). There are new commits occurs regularly. Though the last release (0.9.6) was in 2017. I'm new to the library and don't understand which version should I use in 2019? Thanks.

**Comment by johnynek** [comment]
You should use the latest one on maven.

This is kind of a simple library. We don’t really have problems we fee need to be solved. The main feature is the types themselves: Bijection, Injection and Conversion and how they compose with each other and Function1.

There is also a library of useful instances but most users will make the ones relevant to their situation in their own code base.

If you see an issue, please file it but this library was started about 8 years ago and it basically just works now so it doesn’t need many changes.

**Comment by nartamonov** [comment]
Ok, I got it.
